language: C
env:
  global:
    - IDE_VERSION=1.8.1
    - TEENSY_VERSION=144
matrix:
  include:
    - name: "Arduino Uno"
      env: BOARD=arduino:avr:uno MULTI2C=false
    - name: "Arduino Leonardo"
      env: BOARD=arduino:avr:leonardo MULTI2C=false
    - name: "Arduino Mega"
      env: BOARD=arduino:avr:mega:cpu=atmega2560 MULTI2C=false
    - name: "Teensy LC"
      env: BOARD=teensy:avr:teensyLC:usb=serial,speed=48,opt=osstd,keys=en-us MULTI2C=true

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0

  # Install Arduino IDE
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - sudo mv arduino-$IDE_VERSION /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

  # Install Teensyduino
  - if [[ $BOARD == *"teensy"* ]]; then
      wget https://www.pjrc.com/teensy/td_$TEENSY_VERSION/TeensyduinoInstall.linux64;
      chmod +x ./TeensyduinoInstall.linux64;
      sudo ./TeensyduinoInstall.linux64 --dir=/usr/local/share/arduino;
    fi

  # Sketch Compiling Functions
  - CYAN="\033[36m"; NOC="\033[0m";
  - buildSketchPath() {
      sktch=${1##*/examples};
      sktch=${sktch%/*.ino};
      echo -e "\n${CYAN}Building sketch $sktch.ino${NOC}";
      arduino --verify --board $BOARD "$1";
    }
  - buildExampleSketch() {
      buildSketchPath "$PWD/examples/$1/$2/$2.ino";
    }
  - buildExampleFolder() {
      echo "Building example folder /$1/";
      IFS=$'\n'; set -f;
      for f in $(find $PWD/examples/"$1" -name '*.ino');
      do
        buildSketchPath $f;
      done;
      unset IFS; set +f;
    }
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/NintendoExtensionCtrl
script:
  # Any Controller
  - buildExampleSketch Any DebugPrint
  - buildExampleSketch Any IdentifyController
  - buildExampleSketch Any MultipleTypes
  - buildExampleSketch Any SpeedTest
  - if [ "$MULTI2C" = "true" ]; then
      echo "Board has 2 or more I2C buses";
      buildExampleSketch Any MultipleBus;
    else
      echo "Board has only 1 I2C bus, not building MultipleBus example";
    fi
  
  # Controller-Specific
  - buildExampleFolder "Classic Controller"
  - buildExampleFolder DJ
  - buildExampleFolder Drums
  - buildExampleFolder Guitar
  - buildExampleFolder "NES Mini"
  - buildExampleFolder Nunchuk
  - buildExampleFolder "SNES Mini"

notifications:
  email:
    on_success: change
    on_failure: change
